# title of website
title: ybyml导航

# description of website
description: ybyml's navigation site

# favicon of website
favicon: "https://github.com/ybyml.png?size=40"

# your website url
url: https://ybyml.github.io/ybyml.github.io/

# github profile url
github: "https://github.com/ybyml"

# footer message
footer: © 2022-2029 @ybyml

# template(theme) of your site, available:
# 1. webstack (http://webstack.cc)
template: webstack

# Google analytics
google_analytics: "G-EXE1PJ8CR2"

webstack:
  search:
    enabled: true
    default: google
    # 可选的搜索引擎
    engines:
      - google
      - github
      - weibo
      - baidu
      - bilibili
      - zhihu

content:
  categories:
    - name: 临时收藏
      sites:
        - name: Zerbur
          description: ybyl00@gmail.com登陆,绑定了discord账户，7天试用期
          url: https://dash.zeabur.com/projects
        - name: 在线书签管理工具
          description: 自己把edge收藏夹上传上去了
          url: https://b.lucq.fun
        - name: 即时工具
          description: 致力打造即用即走型在线工具箱
          url: https://www.67tool.com/
        - name: 免费视频床
          description: 据说是某抖的
          url: https://lf3-creative.byteuri.com
        - name: 传文件的
          description: 输入密码后就可以直接提取文件
          url: https://sendfiles.dev/
    - name: yml★★★★★
      sites:
        - name: 甲骨文里的memos
          description: 碎片存放处
          url: https://m.ybyl.eu.org/
        - name: yuan的CF博客
          description: 存放一起技术文章，国内可以访问，但是没图床
          url: https://cfb.ymly.eu.org/
        - name: yuan的小站
          description: 在甲骨文http://129.154.50.164:8888/用宝塔搭的博客，可传图，但访问慢，无法https
          url: http://ybyl.eu.org/
        - name: ymlong的谷歌Blogger
          description: ，国内可访问，图片需要是国内网站地址，建筑图片展示，http也可以
          url: https://www.ybyl.cf/
        - name: ybyl00@126.com的GitHub主页
          description: 放自己的edge收藏夹，直接修改主页的html文件就可以
          url: https://ybyl.github.io/
        - name: gitbook的记录页
          description: 放一些记事，网址之类的
          url: https://ybyl.gitbook.io/ybyl/
        - name: ymiaolong的谷歌blogger博客
          description: 电脑技术类放置点，国外
          url: https://ymiaolong.blogspot.com/       
    - name: 常用推荐
      sites:
        - name: telegra.ph
          description: 可以发布成一个网页，很好用，也可以传小于5m的图片，跟电报有什么关系，不知
          url: https://telegra.ph/
        - name: 甬哥侃侃侃blogger博客
          description: 甬哥侃侃侃YouTube教程
          url: https://ygkkk.blogspot.com/
        - name: jcnf那坨
          description: 一个YouTube主的导航
          url: https://ybfl.xyz/
        - name: LION导航
          description: 需要fq才可以访问
          url: https://dh.kejilion.pro/
        - name: Bio & IT 网址导航
          description: Bio & IT 网址导航
          url: https://nav.bioitee.com/
        - name: 科技lion 谷歌博客
          description: 科技lion的技术文章记录地
          url: https://kejilion.blogspot.com/
        - name: yeelogo
          description: yeelogo在线图标制作平台。
          url: http://yeelogo.com/#/
        - name: v2ex
          description: v2ex技术社区。
          url: https://www.v2ex.com/
        - name: sov2ex
          description: 一个便捷的 v2ex 站内搜索引擎
          url: https://www.sov2ex.com/     
        - name: 发现什么值得买
          description: 分享购物平台。
          url: https://faxian.smzdm.com/
        - name: 西瓜视频
          description: 西瓜视频关注最新
          url: https://www.ixigua.com/my/attention/new
        - name: 京东
          description: 大家都知道的购物站点
          url: https://www.jd.com/
        - name: 花瓣
          description: 收集灵感,保存有用的素材
          url: http://huaban.com/
        - name: 淘宝
          description: 淘东西的地方
          url: https://www.taobao.com/
        - name: CCF
          description: CCF二手区
          url: https://bbs.et8.net/bbs/forumdisplay.php?f=174&pp=35&sort=dateline&order=desc&daysprune=45
    - name: 网络相关
      sites:
        - name: 国内及国际ip访问查询
          description: IP地址查询，网络连通性检查，CDN命中节点测试，DNS出口查询
          url: https://ip.skk.moe/
        - name: 恩山无线论坛
          description: 无线路由刷机等
          url: https://www.right.com.cn/
        - name: 路由器交流
          description: 线路由器使用分享与评测对比
          url: https://www.acwifi.net/
        - name: CloudDrive
          description: CloudDrive /阿里云盘
          url: http://localhost:9798/#/%E9%98%BF%E9%87%8C%E4%BA%91%E7%9B%98?a=1
        - name: ybyl500gnas 
          description: - Synology DiskStation
          url: http://192.168.2.129:5000/
        - name: 坚果云 
          description: 云盘|网盘|企业网盘|同步|备份|无限空间|免费网络硬盘|企业云盘
          url: https://www.jianguoyun.com/
        - name: 华为云 
          description: 存于云间，尽享精彩
          url: https://cloud.huawei.com/#/home
        - name: 小米记事本 
          description: 小米官方笔记本
          url: https://i.mi.com/note/h5#/
    - name: 电影视频
      sites:
        - name: 6v电影网
          description: 6v电影网，最新电影，最新电视剧
          url: https://www.6vhao.net/
        - name: 6v电影-新版
          description: 6v电影-新版
          url: https://www.ai66.cc/
        - name: SSD论坛
          description: CMCT新网址
          url: https://springsunday.net/
        - name: 哔嘀影视（简称BDYS）
          description: 哔嘀影视（简称BDYS），热门电影，最新电影
          url: https://www.bdys01.com/
        - name: 555电影
          description: 555电影-韩国电影免费在线看
          url: https://o8tv.com/
    - name: 软件相关
      sites:
        - name: 吾爱破解
          description: 破解软件论坛
          url: https://www.52pojie.cn/
        - name: 果核剥壳
          description: 互联网的净土
          url: https://www.ghxi.com/
        - name: 卡饭论坛
          description: 浏览器%杀毒等
          url: https://bbs.kafan.cn/forum.php
        - name: 未来软件园
          description: 常用的软件站
          url: http://www.orsoon.com/
        - name: 大眼仔旭
          description: 图像影视处理软件
          url: http://www.dayanzai.me/
        - name: zd423
          description: 软件分享平台领跑
          url: https://www.zdfans.com/
        - name: 小众软件
          description: 分享免费、小巧、实用等
          url: https://www.appinn.com/
        - name: dailydownloaded
          description: 好像是一个国外的软件站
          url: http://windows.dailydownloaded.com/zh/
    - name: 翻越杂项
      sites:
        - name: 甲骨文
          description: 免费中的强大vps（推荐）
          url: https://www.oracle.com/cn/cloud/
        - name: getafreenode
          description: Get A Free Node
          url: https://getafreenode.com/
        - name: 字体仓库
          description: 最全的免费商用字体库
          url: https://www.ziticangku.com/
    - name: 网站工具
      sites:
        - name: speed of cf
          description: CF测速地址，观察抖动（jitter）值
          url: https://speed.cloudflare.com/
        - name: Cloudflare
          description: 全球最大网络服务商
          url: https://dash.cloudflare.com/login/
        - name: freenom
          description: 免费域名服务商
          url: https://www.freenom.com/zh/index.html?lang=zh
        - name: eu.org
          description: 永久免费域名
          url: https://nic.eu.org/arf/en/
    - name: 扬州大学
      sites:
        - name: 扬大主页
          description: yangzhou University
          url: https://www.yzu.edu.cn/index.htm
        - name: 扬大融合门户
          description: 个人门户入口
          url: https://i.yzu.edu.cn
        - name: Eol平台
          description: 在线教学平台
          url: http://eol.yzu.edu.cn/meol/index.do
        - name: 建工
          description: 学院
          url: https://jgxy.yzu.edu.cn/index.htm
        - name: 学校VPN平台
          description: 在线学校VPN平台
          url: https://webvpn.yzu.edu.cn/login
        - name: 图书馆检索
          description: 图书馆检索平台系统
          url: http://opac.yzu.edu.cn:8080/reader/login.php
        - name: 在线教学登记
          description: 在线教学登记平台
          url: http://melab.yzu.edu.cn/jwc/online_edu_pause.asp
        - name: 信息中心
          description: 信息中心软件平台
          url: https://xxhc.yzu.edu.cn/zbrj/
        - name: 扬大邮箱
          description: 扬大腾讯企业邮箱
          url: https://mail.yzu.edu.cn/
        - name: 扬大校历
          description: 扬大2022—2023学年校历图片
          url: https://www.yzu.edu.cn/__local/9/ED/67/85401ACD82F2CD5507CAA17EB1B_646C9196_308940.jpg
    - name: Google产品
      sites:
        - name: Google相册
          description: 长期备份手机照片的地方
          url: https://photos.google.com/
        - name: Gmail
          description: 国外邮箱（缺少不了的）
          url: https://mail.google.com/
        - name: Google keep
          description: Google方便记事本
          url: https://keep.google.com/u/0/
        - name: Google voice
          description: GV电话信息
          url: https://voice.google.com/
        - name: Google 日历
          description: Google记事提醒
          url: https://calendar.google.com/
        - name: Youtube
          description: Google视频平台
          url: https://www.youtube.com/
        - name: Google
          description: 全球最大的搜索引擎
          url: https://www.google.com/
        - name: twitter
          description: 推特
          url: https://twitter.com/home
    - name: 发现产品
      sites:
        - name: 少数派
          description: 高品质数字消费指南
          url: https://sspai.com/
        - name: 小众软件
          description: 在这里发现更多有趣的应用
          url: https://faxian.appinn.com/
        - name: OfficePLUS
          description: OfficePLUS，微软Office官方在线模板网站！
          url: http://www.officeplus.cn/Template/Home.shtml
    - name: 图标素材
      sites:
        - name: Iconfinder
          description: 2,100,000+ free and premium vector icons.
          url: https://www.iconfinder.com
        - name: iconmonstr
          description: Free simple icons for your next project
          url: https://iconmonstr.com/
        - name: FindIcons
          description: Search through 300,000 free icons
          url: https://findicons.com/
        - name: flaticon
          description: 634,000+ Free vector icons in SVG, PSD, PNG, EPS format or as ICON FONT.
          url: https://www.flaticon.com/
        - name: Material icons
          description: Access over 900 material system icons, available in a variety of sizes and densities, and as a web font.
          url: https://material.io/icons/
        - name: Simpleline Icons
          description: Simple line Icons pack
          url: http://simplelineicons.com/
    - name: 摄影图库
      sites:
        - name: wallhaven
          description: 最喜欢的图片库
          url: https://wallhaven.cc/
        - name: Unsplash
          description: Beautiful, free photos.
          url: https://unsplash.com/
        - name: pixabay
          description: 可在任何地方使用的免费图片和视频
          url: https://pixabay.com/
        - name: freenaturestock
          description: Exclusive mindblowing freebies for designers and developers
          url: http://freenaturestock.com/

